# Generated by Django 5.0 on 2023-12-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
